# Configuration for Release Drafter: https://github.com/toolmantim/release-drafter
name-template: 'Version $NEXT_MAJOR_VERSION'
# Most plugins within the Jellyfin Org uses a single-digit versioning. Can be replaced by semver: $MAJOR.$MINOR.$PATCH
# https://github.com/release-drafter/release-drafter#next-version-variables
tag-template: 'v$NEXT_MAJOR_VERSION'
version-template: '$MAJOR'
category-template: '### $TITLE'

# Emoji reference: https://gitmoji.carloscuesta.me/
categories:
  - title: ':boom: Breaking changes'
    labels:
      - breaking
  - title: ':fire: Removed'
    labels:
      - removed
  - title: ':rewind: Reverted Changes'
    labels:
      - revert
      - reverted
  - title: ':rocket: Major features and improvements'
    labels:
      - major-enhancement
      - major-feature
  - title: ':ambulance: Major bug fixes'
    labels:
      - major-bug
  - title: ':wastebasket:️ Deprecated'
    label: deprecated
  - title: ':tada: New features and improvements'
    labels:
      - enhancement
      - feature
  - title: ':bug: Bug Fixes'
    labels:
      - bug
      - fix
      - bugfix
      - regression
  - title: ':white_check_mark: Tests'
    labels:
      - test
      - tests
  - title: ':gear: Code or Repo Maintenance'
    labels:
      - chore
      - cleanup
  - title: ':memo: Documentation updates'
    labels:
      - documentation
  - title: ':arrow_up: Dependency updates'
    labels:
      - dependencies # Default label used by Dependabot
      - dependency
  - title: ':construction_worker: CI & build changes'
    labels:
      - ci
      - build
exclude-labels:
  - no-changelog
  - skip-changelog
  - invalid

autolabeler:
  - label: ci
    files:
      - '.github/workflows/*'
      - '.github/dependabot.yml'
    branch:
      - '/ci\/.+/'
  - label: documentation
    files:
      - '*.md'
    branch:
      - '/docs?\/.+/'
  - label: bug
    branch:
      - '/fix\/.+/'
    title:
      - '/fix/i'
  - label: chore
    branch:
      - '/chore\/.+/'
    title:
      - '/chore/i'
  - label: feature
    branch:
      - '/feature\/.+/'

template: |-
  <!-- Optional: add a release summary here -->
  <!-- FIXME: [Plugin build can be downloaded here](<url to version download>) -->

  ## :sparkles: What's New

  $CHANGES
