---
name: "TubeArchivist Metadata"
guid: "1fa45044-3529-46d5-a08a-6394c1e8d9c8"
version: 4
targetAbi: "10.8.13.0"
framework: "net6.0"
overview: "Short description about your plugin"
description: >
  This is a longer description that can span more than one line and include details about your plugin.

category: "General"
owner: "jellyfin"
artifacts:
  - "Jellyfin.Plugin.TubeArchivistMetadata.dll"
changelog: |-
  - make the guid match throughout the plugin (#25) @snailwaffles
  - ci(deps): bump actions/upload-artifact from 3.1.3 to 4.0.0 (#17) @dependabot
  - ci(deps): bump actions/setup-dotnet from 3 to 4 (#19) @dependabot
  - ci(deps): bump oddstr13/jellyfin-plugin-repository-manager from 1.0.11 to 1.0.12 (#18) @dependabot
  - update readme (#24) @snailwaffles
  - add manifest.json (#22) @snailwaffles
