---
name: "TubeArchivist Metadata"
guid: "1fa45044-3529-46d5-a08a-6394c1e8d9c8"
version: 7
targetAbi: "10.9.2.0"
framework: "net6.0"
overview: "Sync YouTube metadata from TubeArchivist"
description: >
  This plugin syncs metadata from TubeArchivist to Jellyfin, so that it's easy to provide TubeArchivist videos through Jellyfin.

category: "Metadata"
owner: "snailwaffles"
artifacts:
  - "Jellyfin.Plugin.TubeArchivistMetadata.dll"
changelog: |-
  - ci(deps): bump oddstr13/jellyfin-plugin-repository-manager from 1.0.12 to 1.1.0 (#34) @dependabot
  - ci(deps): bump shogo82148/actions-upload-release-asset from 1.7.2 to 1.7.5 (#36) @dependabot
  - ci(deps): bump actions/upload-artifact from 4.0.0 to 4.3.3 (#37) @dependabot
