name: '🚀 Publish Plugin'

on:
  release:
    types:
      - released
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          ref: "master"

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 6.0.x

      - name: Setup jprm
        run: |
          pip install --user jprm

      - name: Build Jellyfin Plugin
        uses: oddstr13/jellyfin-plugin-repository-manager@v1.1.1
        id: jprm
        with:
          dotnet-target: net6.0

      - name: Upload Artifact
        uses: actions/upload-artifact@v4.3.3
        with:
          name: build-artifact
          retention-days: 30
          if-no-files-found: error
          path: ${{ steps.jprm.outputs.artifact }}

      - name: Upload to Release
        id: release
        if: ${{ github.event_name == 'release' }}
        uses: shogo82148/actions-upload-release-asset@v1.7.5
        with:
          upload_url: ${{ github.event.release.upload_url }}
          overwrite: true
          asset_path: ${{ steps.jprm.outputs.artifact }}

      - name: Update manifest
        run: |
          jprm repo add --plugin-url ${{ steps.release.outputs.browser_download_url }} ./manifest.json ${{ steps.jprm.outputs.artifact }}

      - name: Commit manifest
        run: |
          git config user.name jellyfin-bot
          git config user.email team@jellyfin.org
          git pull
          git add ./manifest.json
          git commit -m "Update manifest.json"
          git push --force origin master
